const mongoose = require('mongoose');

const BotCommandSchema = new mongoose.Schema({
  commandKey: { type: String, required: true },
  name: { type: String, required: true },
  description: { type: String, default: '' },
  role: { type: String, enum: ['buyer', 'seller', 'unknown', 'all'], required: true },
  triggerKeywords: [{ type: String }],
  matchType: { type: String, enum: ['exact', 'contains', 'starts_with'], default: 'exact' },
  response: {
    type: { type: String, enum: ['text', 'template', 'dynamic'], default: 'text' },
    text: { type: String, default: '' },
    templateName: { type: String, default: '' },
    templateLanguage: { type: String, default: 'en' },
  },
  isEnabled: { type: Boolean, default: true },
  isBuiltin: { type: Boolean, default: false },
  isDynamic: { type: Boolean, default: false },
  exampleUsage: { type: String, default: '' },
  priority: { type: Number, default: 0 },
}, { timestamps: true });

BotCommandSchema.index({ role: 1, priority: 1 });

module.exports = mongoose.model('BotCommand', BotCommandSchema);

// Default commands seeded on first load
module.exports.DEFAULT_BOT_COMMANDS = [
  // ─── Unknown / New Users ──────────────────────────────────────────────────
  {
    commandKey: 'UNKNOWN_REGISTER',
    name: 'Register / Sign Up',
    description: 'Starts the account registration wizard (3-step: role → name → email)',
    role: 'unknown',
    triggerKeywords: ['register', 'join', 'signup', 'new account', 'start'],
    matchType: 'exact',
    isBuiltin: true,
    isDynamic: false,
    priority: 10,
    exampleUsage: 'REGISTER',
    response: {
      type: 'text',
      text: `👋 Welcome to *PrintMart*!\n\nRegister as:\n1️⃣ *BUYER* – Browse & purchase products\n2️⃣ *SELLER* – List & sell your products\n\nReply *1* or *BUYER* / *2* or *SELLER*`,
    },
  },
  {
    commandKey: 'UNKNOWN_INQUIRE',
    name: 'Guest Inquiry (No Account)',
    description: 'Lets unregistered users send a quick inquiry without signing up',
    role: 'unknown',
    triggerKeywords: ['inquire', 'inquiry', 'enquire', 'enquiry', 'price'],
    matchType: 'exact',
    isBuiltin: true,
    isDynamic: false,
    priority: 20,
    exampleUsage: 'INQUIRE',
    response: {
      type: 'text',
      text: `📩 *Send an Inquiry – No Registration Needed!*\n\nJust tell us what you're looking for:\n\nType your message in this format:\n*Product name | Quantity | Your name*\n\nExample:\n_Business Cards | 500 pcs | Rahul_\n\nWe'll forward your inquiry to relevant sellers and they'll contact you here on WhatsApp! 📱\n\n💡 Register for free to track all your inquiries: reply *REGISTER*`,
    },
  },
  {
    commandKey: 'UNKNOWN_DEFAULT',
    name: 'Default Greeting (Unregistered)',
    description: 'Fallback shown to any unregistered user who sends an unknown message',
    role: 'unknown',
    triggerKeywords: [],
    matchType: 'exact',
    isBuiltin: true,
    isDynamic: false,
    priority: 99,
    exampleUsage: '(any unknown message)',
    response: {
      type: 'text',
      text: `👋 Welcome to *PrintMart*!\n\nYou don't have an account yet.\n\n📝 To register, reply *REGISTER*\n📩 To send an inquiry without registering, reply *INQUIRE*\n🌐 Or sign up at: {SITE_URL}/register`,
    },
  },

  // ─── Buyer Commands ───────────────────────────────────────────────────────
  {
    commandKey: 'BUYER_MENU',
    name: 'Welcome Menu (Buyer)',
    description: 'Main menu shown when buyer sends Hi / Hello / MENU',
    role: 'buyer',
    triggerKeywords: ['hi', 'hello', 'start', 'menu', 'hey'],
    matchType: 'starts_with',
    isBuiltin: true,
    isDynamic: false,
    priority: 10,
    exampleUsage: 'Hi / Hello / MENU',
    response: {
      type: 'text',
      text: `👋 Welcome to *PrintMart*, {NAME}!\n\nI can help you with:\n📦 *1* – Check my inquiries & orders\n📋 *2* – View quotations\n🚚 *3* – Track orders\n🔤 *HELP* – Show all commands\n\nReply with the number or command to continue.`,
    },
  },
  {
    commandKey: 'BUYER_HELP',
    name: 'Help (Buyer)',
    description: 'Shows all available commands for buyers',
    role: 'buyer',
    triggerKeywords: ['help'],
    matchType: 'starts_with',
    isBuiltin: true,
    isDynamic: false,
    priority: 20,
    exampleUsage: 'HELP',
    response: {
      type: 'text',
      text: `*PrintMart Commands (Buyer)*\n\n*STATUS* – View open inquiries & orders\n*ORDERS* – List your recent orders\n*QUOTES* – View pending quotations\n*ACCEPT* – Accept latest quotation\n*REJECT* – Reject latest quotation\n*PAID [order-number]* – Confirm payment\n  e.g.  PAID PM-2024-0001\n*TRACK [order-number]* – Get tracking info\n  e.g.  TRACK PM-2024-0001\n*CANCEL [order-number]* – Cancel order\n*SELLER* – Upgrade account to Seller\n*RESET* – Get a new temporary password\n\nOr just type a message to reply to your latest inquiry.`,
    },
  },
  {
    commandKey: 'BUYER_STATUS',
    name: 'Status (Buyer)',
    description: 'Shows buyer\'s open inquiries and active orders — pulled live from DB',
    role: 'buyer',
    triggerKeywords: ['status'],
    matchType: 'starts_with',
    isBuiltin: true,
    isDynamic: true,
    priority: 30,
    exampleUsage: 'STATUS',
    response: {
      type: 'dynamic',
      text: `📊 *Your Status – PrintMart*\n\n{OPEN_INQUIRIES}\n{ACTIVE_ORDERS}`,
    },
  },
  {
    commandKey: 'BUYER_ORDERS',
    name: 'Orders List (Buyer)',
    description: 'Shows buyer\'s last 8 orders — pulled live from DB',
    role: 'buyer',
    triggerKeywords: ['orders'],
    matchType: 'starts_with',
    isBuiltin: true,
    isDynamic: true,
    priority: 40,
    exampleUsage: 'ORDERS',
    response: {
      type: 'dynamic',
      text: `📦 *Your Orders – PrintMart*\n\n{ORDER_LIST}\n\nReply *TRACK [order-number]* for tracking details.`,
    },
  },
  {
    commandKey: 'BUYER_QUOTES',
    name: 'View Quotations (Buyer)',
    description: 'Shows buyer\'s pending quotations — pulled live from DB',
    role: 'buyer',
    triggerKeywords: ['quotes', 'quote'],
    matchType: 'exact',
    isBuiltin: true,
    isDynamic: true,
    priority: 50,
    exampleUsage: 'QUOTES',
    response: {
      type: 'dynamic',
      text: `📋 *Pending Quotations – PrintMart*\n\n{QUOTATION_LIST}\n\nReply *ACCEPT* to accept the latest or *ACCEPT Q-[ref]* for specific.`,
    },
  },
  {
    commandKey: 'BUYER_ACCEPT',
    name: 'Accept Quotation (Buyer)',
    description: 'Buyer accepts a quotation → auto-creates order and notifies seller',
    role: 'buyer',
    triggerKeywords: ['accept'],
    matchType: 'starts_with',
    isBuiltin: true,
    isDynamic: true,
    priority: 60,
    exampleUsage: 'ACCEPT  or  ACCEPT Q-ABC123',
    response: {
      type: 'dynamic',
      text: `🎉 *Order Confirmed – PrintMart*\n\n*Order No:* {ORDER_NUMBER}\n*Total:* ₹{TOTAL}\n\nPlease make payment and reply: *PAID {ORDER_NUMBER}*`,
    },
  },
  {
    commandKey: 'BUYER_REJECT',
    name: 'Reject Quotation (Buyer)',
    description: 'Buyer rejects a quotation and notifies seller',
    role: 'buyer',
    triggerKeywords: ['reject'],
    matchType: 'starts_with',
    isBuiltin: true,
    isDynamic: true,
    priority: 70,
    exampleUsage: 'REJECT  or  REJECT Q-ABC123',
    response: { type: 'dynamic', text: `❌ Quotation rejected. The vendor has been notified.` },
  },
  {
    commandKey: 'BUYER_PAID',
    name: 'Confirm Payment (Buyer)',
    description: 'Buyer marks payment as done for an order',
    role: 'buyer',
    triggerKeywords: ['paid'],
    matchType: 'starts_with',
    isBuiltin: true,
    isDynamic: true,
    priority: 75,
    exampleUsage: 'PAID PM-2024-0001',
    response: {
      type: 'dynamic',
      text: `✅ *Payment Confirmed – PrintMart*\n\n*Order:* {ORDER_NUMBER}\n*Amount:* ₹{TOTAL}\n\nYour payment has been confirmed. Your order is now being processed.`,
    },
  },
  {
    commandKey: 'BUYER_TRACK',
    name: 'Track Order (Buyer)',
    description: 'Shows tracking info for a specific order — pulled live from DB',
    role: 'buyer',
    triggerKeywords: ['track'],
    matchType: 'starts_with',
    isBuiltin: true,
    isDynamic: true,
    priority: 80,
    exampleUsage: 'TRACK PM-2024-0001',
    response: {
      type: 'dynamic',
      text: `🚚 *Tracking – {ORDER_NUMBER}*\n\n*Status:* {STATUS}\n*Tracking:* {TRACKING_INFO}\n*Total:* ₹{TOTAL}\n*Payment:* {PAYMENT_STATUS}`,
    },
  },
  {
    commandKey: 'BUYER_CANCEL',
    name: 'Cancel Order (Buyer)',
    description: 'Buyer cancels an order (not allowed if dispatched/delivered)',
    role: 'buyer',
    triggerKeywords: ['cancel'],
    matchType: 'starts_with',
    isBuiltin: true,
    isDynamic: true,
    priority: 90,
    exampleUsage: 'CANCEL PM-2024-0001',
    response: { type: 'dynamic', text: `❌ *Order Cancelled – PrintMart*\n\n*Order:* {ORDER_NUMBER}\nContact support if you have questions.` },
  },
  {
    commandKey: 'BUYER_SELLER_UPGRADE',
    name: 'Upgrade to Seller',
    description: 'Buyer requests to upgrade their account to seller role',
    role: 'buyer',
    triggerKeywords: ['seller'],
    matchType: 'exact',
    isBuiltin: true,
    isDynamic: false,
    priority: 100,
    exampleUsage: 'SELLER',
    response: {
      type: 'text',
      text: `🏪 *Become a Seller on PrintMart*\n\nAs a seller you can:\n✅ List your products & services\n✅ Receive buyer inquiries\n✅ Send quotations & manage orders\n✅ Get WhatsApp lead notifications\n\nReply *YES* to upgrade your account to Seller.\nReply *NO* to cancel.`,
    },
  },
  {
    commandKey: 'BUYER_RESET',
    name: 'Password Reset (Buyer)',
    description: 'Resets buyer password and sends a temporary password via WhatsApp',
    role: 'buyer',
    triggerKeywords: ['reset'],
    matchType: 'exact',
    isBuiltin: true,
    isDynamic: true,
    priority: 110,
    exampleUsage: 'RESET',
    response: {
      type: 'dynamic',
      text: `🔑 *Password Reset*\n\nYour new temporary password:\n\n*{TEMP_PASSWORD}*\n\n🔗 Login: {SITE_URL}/login\n\n⚠️ Change your password after login via Profile settings.`,
    },
  },

  // ─── Seller Commands ──────────────────────────────────────────────────────
  {
    commandKey: 'SELLER_MENU',
    name: 'Welcome Menu (Seller)',
    description: 'Main menu shown when seller says Hi / Hello / MENU',
    role: 'seller',
    triggerKeywords: ['hi', 'hello', 'start', 'menu', 'hey'],
    matchType: 'starts_with',
    isBuiltin: true,
    isDynamic: false,
    priority: 10,
    exampleUsage: 'Hi / Hello / MENU',
    response: {
      type: 'text',
      text: `👋 Welcome back, *{NAME}*!\n\nQuick commands:\n📨 *STATUS* – Pending inquiries & orders\n💰 *QUOTE [amount]* – Send quotation for latest inquiry\n   e.g.  QUOTE 5000\n🚚 *DISPATCH [order] [tracking]* – Mark dispatched\n   e.g.  DISPATCH PM-2024-0001 TRK123\n✅ *DELIVER [order]* – Mark delivered\n   e.g.  DELIVER PM-2024-0001\n🔤 *HELP* – Show all commands`,
    },
  },
  {
    commandKey: 'SELLER_HELP',
    name: 'Help (Seller)',
    description: 'Shows all available commands for sellers/vendors',
    role: 'seller',
    triggerKeywords: ['help'],
    matchType: 'starts_with',
    isBuiltin: true,
    isDynamic: false,
    priority: 20,
    exampleUsage: 'HELP',
    response: {
      type: 'text',
      text: `*PrintMart Commands (Vendor)*\n\n*STATUS* – Pending inquiries & active orders\n*QUOTE [amount]* – Quotation for latest inquiry\n  e.g.  QUOTE 5000\n*QUOTE [inq-prefix] [amount]* – Specific inquiry\n  e.g.  QUOTE INQ123 8000\n*DISPATCH [order] [tracking]* – Mark dispatched\n  e.g.  DISPATCH PM-2024-0001 DTDC-TRK789\n*DELIVER [order]* – Mark as delivered\n  e.g.  DELIVER PM-2024-0001\n*ORDERS* – Active orders summary\n*BUYER* – Info on browsing & buying as a seller\n*RESET* – Get a new temporary password\n\nOr just reply to this chat to respond to an inquiry.`,
    },
  },
  {
    commandKey: 'SELLER_STATUS',
    name: 'Status (Seller)',
    description: 'Shows seller\'s pending inquiries and active orders — pulled live from DB',
    role: 'seller',
    triggerKeywords: ['status'],
    matchType: 'starts_with',
    isBuiltin: true,
    isDynamic: true,
    priority: 30,
    exampleUsage: 'STATUS',
    response: {
      type: 'dynamic',
      text: `📊 *Vendor Status – PrintMart*\n\n{PENDING_INQUIRIES}\n{ACTIVE_ORDERS}`,
    },
  },
  {
    commandKey: 'SELLER_ORDERS',
    name: 'Orders List (Seller)',
    description: 'Shows seller\'s last 8 orders — pulled live from DB',
    role: 'seller',
    triggerKeywords: ['orders'],
    matchType: 'starts_with',
    isBuiltin: true,
    isDynamic: true,
    priority: 40,
    exampleUsage: 'ORDERS',
    response: {
      type: 'dynamic',
      text: `📦 *Your Orders – PrintMart*\n\n{ORDER_LIST}`,
    },
  },
  {
    commandKey: 'SELLER_QUOTE',
    name: 'Send Quotation (Seller)',
    description: 'Seller sends a quotation to a buyer: QUOTE [amount] or QUOTE [ref] [amount]',
    role: 'seller',
    triggerKeywords: ['quote '],
    matchType: 'starts_with',
    isBuiltin: true,
    isDynamic: true,
    priority: 50,
    exampleUsage: 'QUOTE 5000  or  QUOTE INQ-ABC123 8000',
    response: {
      type: 'dynamic',
      text: `✅ Quotation Q-{REF} sent to {BUYER_NAME} for ₹{AMOUNT}`,
    },
  },
  {
    commandKey: 'SELLER_DISPATCH',
    name: 'Dispatch Order (Seller)',
    description: 'Marks an order as dispatched with optional tracking number',
    role: 'seller',
    triggerKeywords: ['dispatch '],
    matchType: 'starts_with',
    isBuiltin: true,
    isDynamic: true,
    priority: 60,
    exampleUsage: 'DISPATCH PM-2024-0001 TRK-DTDC-789',
    response: {
      type: 'dynamic',
      text: `✅ Order {ORDER_NUMBER} marked as dispatched with tracking: {TRACKING}`,
    },
  },
  {
    commandKey: 'SELLER_DELIVER',
    name: 'Deliver Order (Seller)',
    description: 'Marks an order as delivered (must be in dispatched status first)',
    role: 'seller',
    triggerKeywords: ['deliver '],
    matchType: 'starts_with',
    isBuiltin: true,
    isDynamic: true,
    priority: 70,
    exampleUsage: 'DELIVER PM-2024-0001',
    response: {
      type: 'dynamic',
      text: `📦 *Order Marked Delivered – PrintMart*\n\n*Order:* {ORDER_NUMBER}\n\nOrder {ORDER_NUMBER} has been marked as delivered.`,
    },
  },
  {
    commandKey: 'SELLER_BUYER_MODE',
    name: 'Buyer Mode Info (Seller)',
    description: 'Tells sellers how they can also browse as buyers',
    role: 'seller',
    triggerKeywords: ['buyer'],
    matchType: 'exact',
    isBuiltin: true,
    isDynamic: false,
    priority: 80,
    exampleUsage: 'BUYER',
    response: {
      type: 'text',
      text: `🛒 *Buyer Mode*\n\nAs a seller on PrintMart, you can also browse and inquire about products as a buyer.\n\nVisit the app to:\n• Browse products\n• Send inquiries to other sellers\n• Compare prices\n\n🔗 {SITE_URL}/products\n\nYour seller dashboard remains active. Reply *MENU* for seller commands.`,
    },
  },
  {
    commandKey: 'SELLER_RESET',
    name: 'Password Reset (Seller)',
    description: 'Resets seller password and sends a temporary password via WhatsApp',
    role: 'seller',
    triggerKeywords: ['reset'],
    matchType: 'exact',
    isBuiltin: true,
    isDynamic: true,
    priority: 90,
    exampleUsage: 'RESET',
    response: {
      type: 'dynamic',
      text: `🔑 *Password Reset*\n\nYour new temporary password:\n\n*{TEMP_PASSWORD}*\n\n🔗 Login: {SITE_URL}/login\n\n⚠️ Change your password after login via Profile settings.`,
    },
  },
];
